# Generated by Django 6.1.1 on 2026-09-21 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('las_ricuras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plato',
            name='categoria',
            field=models.CharField(choices=[('entradas', 'Entradas'), ('platos_fuertes', 'Platos fuertes'), ('postres', 'Postres'), ('bebidas', 'Bebidas')], default='platos_fuertes', max_length=30),
        ),
    ]
